#DB: H2 인메모리
#
#외부 서비스: Mock 또는 테스트 키
#
#JWT: 테스트용 시크릿
# src/main/resources/application-test.yml

server:
  port: 8080

spring:
  jwt:
    access-secret: test-access-secret
    refresh-secret: test-refresh-secret
    access-token-validity-in-ms: 600000
    refresh-token-validity-in-ms: 1209600000
  application:
    name: mt-server
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
mybatis:
  type-aliases-package: com.mungtrainer.mtserver
  type-handlers-package: com.mungtrainer.mtserver.typehandler
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
  mapper-locations: classpath:mapper/**/*.xml
aws:
  s3:
    bucket: test-bucket
    accessKeyId: test-access-key
    secretAccessKey: test-secret
    region: ap-northeast-2
    presigned-url:
      expiration-minutes: 10
