name: CI - Build & Push Image + Update Manifest Repo
on:
  push:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # 1. App Repo Checkout
      - name: Checkout app repository
        uses: actions/checkout@v4

      # 2. JDK 17 설치
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # 4. Gradle Build (테스트 스킵, main/resources/application.yml 사용)
      - name: Build jar
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test --no-daemon

      # 5. Docker 이미지 빌드 (commit sha tag)
      - name: Docker build
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USER }}/web-app:${{ github.sha }} .

      # 6. DockerHub 로그인
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # 7. Docker 이미지 Push
      - name: Docker push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/web-app:${{ github.sha }}

      # 7. Manifest Repo Checkout (GitOps Repo)
      - name: Checkout manifest repository
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.MANIFEST_REPO }} # ← 여기 Manifest Repo 주소
          token: ${{ secrets.MANIFEST_REPO_TOKEN }}
          path: manifests

      # 8. kustomization.yaml image tag 업데이트 (overlays/dev 기준)
      - name: Update k8s image tag
        run: |
          sed -i \
          "s/newTag: .*/newTag: ${{ github.sha }}/" \
          manifests/overlays/dev/kustomization.yaml

      # 9. Manifest Repo Commit & Push
      - name: Commit & Push manifest repo
        run: |
          cd manifests
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add overlays/dev/kustomization.yaml
          git commit -m "chore(dev): update web-app image to ${{ github.sha }}"
          git push